# Generated by Django 3.2.9 on 2021-11-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=2083)),
                ('yumFactor', models.IntegerField(max_length=2)),
            ],
        ),
    ]
