# Generated by Django 3.2.9 on 2021-11-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cake',
            name='yumFactor',
            field=models.IntegerField(max_length=1),
        ),
    ]
